src/GeekStream.Web/Controllers/ArticleController.cs
using System.Threading.Tasks;
using GeekStream.Core.Services;
using GeekStream.Core.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GeekStream.Controllers
{
    public class ArticleController : Controller
    {
        private readonly CategoryService _categoryService;
        private readonly ArticleService _articleService;
        private readonly ReviewService _reviewService;

        public ArticleController(
            CategoryService categoryService,
            ArticleService articleService,
            ReviewService reviewService)
        {
            _categoryService = categoryService;
            _articleService = articleService;
            _reviewService = reviewService;
        }
        
        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.Categories = _categoryService.GetCategories();
            return View();
        }
        
        [HttpGet]
        public IActionResult Read(int id)
        {
            var article = _articleService.GetArticleById(id);
            return View(new ReadArticleViewModel
            {
                Article = article
            });
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateArticleViewModel model)
        {
            ViewBag.Categories = _categoryService.GetCategories();
            if (!ModelState.IsValid) return View();
            var articleId = await _articleService.CreateArticle(model, User, false);
            if (articleId < 0)
            {
                ModelState.AddModelError("", "Не удалось создать статью");
                return View();
            }

            var reviewId = _reviewService.CreateReview(articleId);
            return RedirectToAction("Review", "Review", new { id = reviewId});
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Draft(int id)
        {
            ViewBag.Categories = _categoryService.GetCategories();
            var model = await _articleService.GetDraftViewModelById(id, User);
            if (model == null) return NotFound();
            return View(model);
        }
        
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> MyDrafts()
        {
            var model = await _articleService.GetUserDrafts(User);
            if (model == null) return NotFound();
            return View(model);
        }
        
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SaveAsDraft(CreateArticleViewModel model)
        {
            ViewBag.Categories = _categoryService.GetCategories();
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var articleId = await _articleService.CreateArticle(model, User, true);
            return RedirectToAction("Draft", new {id = articleId});
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult SaveDraft(DraftViewModel model)
        {
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var articleId = model.Id;
            _articleService.UpdateDraft(model);
            return RedirectToAction("Draft", new {id = articleId});
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult Publish(int reviewId)
        {
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var articleId = _articleService.Publish(reviewId);
            return RedirectToAction("Read", new {id = articleId});
        }
        
        [HttpGet]
        [Authorize]
        public IActionResult Unpublish(int articleId)
        {
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var article = _articleService.GetArticleById(articleId);
            if (User.Identity.Name != article.Author.UserName && !User.IsInRole("Admin") && !User.IsInRole("Mod"))
                return RedirectToAction("Articles", "Home");
            _articleService.Unpublish(articleId);
            return RedirectToAction("Draft", new {id = articleId});
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult Remove(int id)
        {
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var article = _articleService.GetArticleById(id);
            if (article == null || !article.IsDraft && article.PublishedDate != null) return RedirectToAction("Articles", "Home");
            if (User.Identity.Name != article.Author.UserName && !User.IsInRole("Admin") && !User.IsInRole("Mod"))
                return RedirectToAction("Articles", "Home");
            _articleService.Remove(article);
            return RedirectToAction("Articles", "Home");
        }
    }
}

src/GeekStream.Web/Controllers/AuthorController.cs
using System.Linq;
using System.Threading.Tasks;
using GeekStream.Core.Shared.Entities;
using GeekStream.Core.Shared.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GeekStream.Controllers
{
    public class AuthorController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        public AuthorController(
            UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }
        
        [HttpGet]
        public async Task<IActionResult> Show(string id)
        {
            var user = await _userManager.Users
                .Include(x => x.Articles)
                    .ThenInclude(x => x.Category)
                    .AsSplitQuery()
                .Include(x => x.Articles)
                    .ThenInclude(x => x.Comments)
                    .AsSplitQuery()
                .Include(x => x.Articles)
                    .ThenInclude(x => x.ArticleVotes)
                    .AsSplitQuery()
                .FirstOrDefaultAsync(x => x.Id == id); 
            return View(user);
        }

        [HttpGet]
        public IActionResult List()
        {
            var users = _userManager.Users.ToList();
            return View(users);
        }
    }
}

src/GeekStream.Web/Controllers/CategoryController.cs
using GeekStream.Core.Shared.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace GeekStream.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;

        public CategoryController(
            ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }
        
        [HttpGet]
        public IActionResult Show(int id)
        {
            var category = _categoryRepository.GetCategoryById(id);
            return View(category);
        }
        
        [HttpGet]
        public IActionResult List()
        {
            var categories = _categoryRepository.GetCategories();
            return View(categories);
        }
    }
}

src/GeekStream.Web/Views/Article/Create.cshtml
@model GeekStream.Core.ViewModels.CreateArticleViewModel

@{
    ViewData["Title"] = "Новая статья";
}

<div class="bg-white">
    <div class="container pt-3">
        <form style="color: #838383;">
            <div class="row py-3 align-items-center">
                <div>Новая статья</div>
                <div class="ml-auto">
                    <input type="submit" formaction="@Url.Action("SaveAsDraft")" formmethod="post" class="btn btn-light" style="border: 1px solid lightgray; border-radius: 8px" value="Сохранить черновик">
                    <input type="submit" formaction="@Url.Action("Create")" formmethod="post" class="btn" style="background-color: #7B61FF; color: white; border-radius: 8px" value="Опубликовать">
                </div>
            </div>
            <div class="row form-group">
                <div class="d-flex flex-column">
                    <label asp-for="Title" class="small"></label>
                    <span asp-validation-for="Title" class="text-danger small"></span>
                </div>
                <input asp-for="Title" class="form-control" style="border-radius: 8px" placeholder="Придумайте название статьи">
                <span class="text-muted small">Хорошее название может заинтересовать многих читателей</span>
            </div>
            <div class="row form-group">
                <label asp-for="CategoryId" class="small"></label>
                <select
                    asp-for="CategoryId" class="form-control" style="border-radius: 8px"
                    asp-items="@(new SelectList(ViewBag.Categories, "Id", "Name"))"></select>
                <span class="text-muted small">Статью можно отправить в одну категорию</span>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="row form-group">
                <label asp-for="Keywords" class="small"></label>
                <input asp-for="Keywords" class="form-control" style="border-radius: 8px" placeholder="Введите ключевые слова">
                <span class="text-muted small">Ключевые слова помогают найти вашу статью в поиске</span>
                <span asp-validation-for="Keywords" class="text-danger"></span>
            </div>
            <div class="row form-group">
                <div class="d-flex flex-column">
                    <label asp-for="Content" class="small"></label>
                    <span asp-validation-for="Content" class="text-danger small"></span>
                </div>
                <textarea asp-for="Content" class="form-control" style="border-radius: 8px; resize: none" rows="38" placeholder="Ваша интересная статья">
                </textarea>
            </div>
        </form>
    </div>
    
</div>

src/GeekStream.Web/Views/Article/Draft.cshtml
@model GeekStream.Core.ViewModels.DraftViewModel

@{
    ViewData["Title"] = "Черновик";
}

<div class="bg-white">
    <div class="container pt-3">
        <form style="color: #838383;">
            <input asp-for="Id" hidden>
            <div class="row py-3 align-items-center">
                <div>Редактировать черновик</div>
                <div class="ml-auto">
                    <input type="submit" formaction="@Url.Action("Remove")" formmethod="post" class="btn btn-light" style="border: 1px solid lightgray; border-radius: 8px" value="Удалить черновик">
                    <input type="submit" formaction="@Url.Action("SaveDraft")" formmethod="post" class="btn btn-light" style="border: 1px solid lightgray; border-radius: 8px" value="Сохранить изменения">
                    <input type="submit" formaction="@Url.Action("CreateReview", "Review", new { articleId = Model.Id})" formmethod="post" class="btn" style="background-color: #7B61FF; color: white; border-radius: 8px" value="Опубликовать">
                </div>
            </div>
            <div class="row form-group">
                <div class="d-flex flex-column">
                    <label asp-for="Title" class="small"></label>
                    <span asp-validation-for="Title" class="text-danger small"></span>
                </div>
                <input asp-for="Title" class="form-control" style="border-radius: 8px" placeholder="Придумайте название статьи">
                <span class="text-muted small">Хорошее название может заинтересовать многих читателей</span>
            </div>
            <div class="row form-group">
                <label asp-for="CategoryId" class="small"></label>
                <select
                    asp-for="CategoryId" class="form-control" style="border-radius: 8px"
                    asp-items="@(new SelectList(ViewBag.Categories, "Id", "Name"))"></select>
                <span class="text-muted small">Статью можно отправить в одну категорию</span>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="row form-group">
                <label asp-for="Keywords" class="small"></label>
                <input asp-for="Keywords" class="form-control" style="border-radius: 8px" placeholder="Введите ключевые слова">
                <span class="text-muted small">Ключевые слова помогают найти вашу статью в поиске</span>
                <span asp-validation-for="Keywords" class="text-danger"></span>
            </div>
            <div class="row form-group">
                <div class="d-flex flex-column">
                    <label asp-for="Content" class="small"></label>
                    <span asp-validation-for="Content" class="text-danger small"></span>
                </div>
                <textarea asp-for="Content" class="form-control" style="border-radius: 8px; resize: none" rows="38" placeholder="Ваша интересная статья">
                </textarea>
            </div>
        </form>
    </div>
    
</div>

src/GeekStream.Web/Views/Article/MyDrafts.cshtml
@model IEnumerable<GeekStream.Core.ViewModels.DraftsViewModel>

@{
    ViewData["Title"] = "Мои черновики";
}

<div class="container pt-3">
    @foreach (var article in Model)
    {
        <div class="container bg-white mb-3" style="border-radius: 8px; padding: 24px">
            <div class="row align-items-center">
                <div class="col-md-auto">
                    @if (article.Category.IconPath == null)
                    {
                        <div style="width: 24px; height: 24px; background-color: #7B61FF; border-radius: 4px"></div>
                    }
                    else
                    {
                        <img src="~/@article.Category.IconPath" width="24" height="24" alt="CategoryIcon">
                    }
                </div>
                <a class="col-md-auto pl-0" href="#">@article.Category.Name</a>
                <div class="col-md-auto text-muted small">Создано: @article.CreatedDate.ToString("dd/MM/yyyy HH:mm")</div>
            </div>
            <div class="row align-items-center mt-3">
                <a class="text-muted" asp-controller="Article" asp-action="Draft" asp-route-id="@article.Id">
                    <h5 class="col-md-auto">@article.Title</h5>
                </a>
            </div>
            <div class="small text-muted">
                @article.Content
            </div>
        </div>
    }
</div>

src/GeekStream.Web/Views/Article/Read.cshtml
@using GeekStream.Core.Shared.Entities
@using GeekStream.Core.ViewModels
@model GeekStream.Core.ViewModels.ReadArticleViewModel

@{
    ViewData["Title"] = Model.Article.Title;
}

<div class="container pt-3">
    <div class="container bg-white mb-3" style="border-radius: 8px; padding: 24px">
        <div class="row align-items-center">
            <div class="col-md-auto">
                @if (Model.Article.Category.IconPath == null)
                {
                    <div style="width: 24px; height: 24px; background-color: #7B61FF; border-radius: 4px"></div>
                }
                else
                {
                    <img src="~/@Model.Article.Category.IconPath" width="24" height="24" alt="CategoryIcon">
                }
            </div>
            <a class="col-md-auto pl-0" asp-controller="Category" asp-action="Show" asp-route-id="@Model.Article.Category.Id">@Model.Article.Category.Name</a>
            <div class="col-md-auto text-muted small">@DateTime.Parse(Model.Article.PublishedDate.ToString()).ToString("dd/MM/yyyy HH:mm")</div>
            @if (User.Identity.Name == Model.Article.Author.UserName || User.IsInRole("Admin") || User.IsInRole("Mod"))
            {
                <a class="btn col-md-auto ml-auto" style="background-color: #7B61FF; color: white; border-radius: 8px" asp-controller="Article" asp-action="Unpublish" asp-route-articleId="@Model.Article.Id">Снять с публикации</a>   
            }
        </div>
        <div class="row align-items-center ">
            <h3 class="col-md-auto pt-2">@Model.Article.Title</h3>
        </div>
        <div class="text-muted py-2">
            @Model.Article.Content
        </div>
        <div class="col-md-auto ml-auto d-flex flex-row align-items-center pl-0">
            @{
                var avatarPath = Model.Article.Author.AvatarPath ?? "imgs/avatars/default.png";
            }
            <img src="~/@avatarPath" alt="avatar" width="36" height="36" style="border-radius: 18px">
            <a asp-controller="Author" asp-action="Show" asp-route-id="@Model.Article.Author.Id" class="nav-link pl-2">@Model.Article.Author.FirstName @Model.Article.Author.LastName</a>
        </div>
        <div class="text-muted pt-3">
            Комментарии (@Model.Article.Comments.Count)
        </div>
        <div class="py-1">
            @if (Model.Article.Comments.Count == 0)
            {
                <div class="text-center">
                    <h5>Упс, кажется, у этой статьи ещё нет комменариев</h5>
                    <h6>Станьте первым комментатором :)</h6>
                </div>
            }
            else
            {
                foreach (var comment in Model.Article.Comments)
                {
                    <div class="my-2">
                        <div class="col-md-auto d-flex flex-row align-items-center pl-0">
                            @{
                                var avatarPathComment = comment.Author.AvatarPath ?? "imgs/avatars/default.png";
                            }
                            <img src="~/@avatarPathComment" alt="avatar" width="24" height="24" style="border-radius: 18px">
                            <a asp-controller="Author" asp-action="Show" asp-route-id="@comment.Author.Id" class="nav-link pl-2">@comment.Author.FirstName @comment.Author.LastName</a>
                        </div>
                        <div class="text-muted">
                            @comment.Text
                        </div>
                    </div>
                }
            }
        </div>
        @{ await Html.RenderPartialAsync("_sendCommentPartial", new SendCommentViewModel
           {
               ArticleId = Model.Article.Id
           }); }
    </div>
</div>