src/GeekStream.Web/Controllers/ArticleController.cs
using System.Threading.Tasks;
using GeekStream.Core.Services;
using GeekStream.Core.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GeekStream.Controllers
{
    public class ArticleController : Controller
    {
        private readonly CategoryService _categoryService;
        private readonly ArticleService _articleService;
        private readonly ReviewService _reviewService;

        public ArticleController(
            CategoryService categoryService,
            ArticleService articleService,
            ReviewService reviewService)
        {
            _categoryService = categoryService;
            _articleService = articleService;
            _reviewService = reviewService;
        }
        
        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.Categories = _categoryService.GetCategories();
            return View();
        }
        
        [HttpGet]
        public IActionResult Read(int id)
        {
            var article = _articleService.GetArticleById(id);
            return View(new ReadArticleViewModel
            {
                Article = article
            });
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateArticleViewModel model)
        {
            ViewBag.Categories = _categoryService.GetCategories();
            if (!ModelState.IsValid) return View();
            var articleId = await _articleService.CreateArticle(model, User, false);
            if (articleId < 0)
            {
                ModelState.AddModelError("", "Не удалось создать статью");
                return View();
            }

            var reviewId = _reviewService.CreateReview(articleId);
            return RedirectToAction("Review", "Review", new { id = reviewId});
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Draft(int id)
        {
            ViewBag.Categories = _categoryService.GetCategories();
            var model = await _articleService.GetDraftViewModelById(id, User);
            if (model == null) return NotFound();
            return View(model);
        }
        
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> MyDrafts()
        {
            var model = await _articleService.GetUserDrafts(User);
            if (model == null) return NotFound();
            return View(model);
        }
        
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SaveAsDraft(CreateArticleViewModel model)
        {
            ViewBag.Categories = _categoryService.GetCategories();
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var articleId = await _articleService.CreateArticle(model, User, true);
            return RedirectToAction("Draft", new {id = articleId});
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult SaveDraft(DraftViewModel model)
        {
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var articleId = model.Id;
            _articleService.UpdateDraft(model);
            return RedirectToAction("Draft", new {id = articleId});
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult Publish(int reviewId)
        {
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var articleId = _articleService.Publish(reviewId);
            return RedirectToAction("Read", new {id = articleId});
        }
        
        [HttpGet]
        [Authorize]
        public IActionResult Unpublish(int articleId)
        {
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var article = _articleService.GetArticleById(articleId);
            if (User.Identity.Name != article.Author.UserName && !User.IsInRole("Admin") && !User.IsInRole("Mod"))
                return RedirectToAction("Articles", "Home");
            _articleService.Unpublish(articleId);
            return RedirectToAction("Draft", new {id = articleId});
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult Remove(int id)
        {
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var article = _articleService.GetArticleById(id);
            if (article == null || !article.IsDraft && article.PublishedDate != null) return RedirectToAction("Articles", "Home");
            if (User.Identity.Name != article.Author.UserName && !User.IsInRole("Admin") && !User.IsInRole("Mod"))
                return RedirectToAction("Articles", "Home");
            _articleService.Remove(article);
            return RedirectToAction("Articles", "Home");
        }
    }
}

src/GeekStream.Web/Controllers/AuthorController.cs
using System.Linq;
using System.Threading.Tasks;
using GeekStream.Core.Shared.Entities;
using GeekStream.Core.Shared.Repositories;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace GeekStream.Controllers
{
    public class AuthorController : Controller
    {
        private readonly UserManager<AppUser> _userManager;

        public AuthorController(
            UserManager<AppUser> userManager)
        {
            _userManager = userManager;
        }
        
        [HttpGet]
        public async Task<IActionResult> Show(string id)
        {
            var user = await _userManager.Users
                .Include(x => x.Articles)
                    .ThenInclude(x => x.Category)
                    .AsSplitQuery()
                .Include(x => x.Articles)
                    .ThenInclude(x => x.Comments)
                    .AsSplitQuery()
                .Include(x => x.Articles)
                    .ThenInclude(x => x.ArticleVotes)
                    .AsSplitQuery()
                .FirstOrDefaultAsync(x => x.Id == id); 
            return View(user);
        }

        [HttpGet]
        public IActionResult List()
        {
            var users = _userManager.Users.ToList();
            return View(users);
        }
    }
}

src/GeekStream.Web/Controllers/CategoryController.cs
using GeekStream.Core.Shared.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace GeekStream.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;

        public CategoryController(
            ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }
        
        [HttpGet]
        public IActionResult Show(int id)
        {
            var category = _categoryRepository.GetCategoryById(id);
            return View(category);
        }
        
        [HttpGet]
        public IActionResult List()
        {
            var categories = _categoryRepository.GetCategories();
            return View(categories);
        }
    }
}

src/GeekStream.Web/Controllers/CommentController.cs
using System.Threading.Tasks;
using GeekStream.Core.Services;
using GeekStream.Core.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GeekStream.Controllers
{
    public class CommentController : Controller
    {
        private readonly CommentService _commentService;

        public CommentController(CommentService commentService)
        {
            _commentService = commentService;
        }
        
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SendComment(SendCommentViewModel model)
        {
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            
            await _commentService.SendComment(model, User);
            
            return RedirectToAction("Read", "Article", new {id = model.ArticleId});
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SendReviewComment(SendReviewCommentViewModel model)
        {
            if (!ModelState.IsValid) return RedirectToAction("Review", "Review", new { id = model.ReviewId});

            await _commentService.SendReviewComment(model, User);
            
            return RedirectToAction("Review", "Review", new {id = model.ReviewId});
        }
    }
}

src/GeekStream.Web/Views/Shared/Info.cshtml
@{
    ViewData["Title"] = ViewBag.Title;
    var style = ViewBag.IsError ? "text-danger" : "text-success";
}
<div class="row text-center">
    <div class="col-md-6 offset-3 bg-light mt-3" style="border-radius: 16px">
        <div class="col-md-10 offset-1 my-auto">
            <div class="col-md-auto" style="margin-top: 35px">
                <img src="~/imgs/brand.png" alt="logo" height="40px">
            </div>
            <div class="col-md-auto mb-1 @style">
                <h2>@ViewBag.Title</h2>
            </div>
            <div class="@style">
                <h5>@ViewBag.Description</h5>
            </div>
        </div>
    </div>
</div>

src/GeekStream.Web/Views/Shared/_Layout.cshtml
@using GeekStream.Core.Shared.Entities
@inject SignInManager<AppUser> _signInManager
@inject UserManager<AppUser> _userManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"]</title>
    <link rel="shortcut icon" type="image/png" href="~/imgs/brand.png"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter&display=swap" rel="stylesheet">
</head>
<body style="background-color: #E5E5E5; font-family: 'Inter', sans-serif;">
<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-white border" style="height: 80px">
        <a asp-controller="Home" asp-action="Articles" class="navbar-brand">
            <img src="~/imgs/brand.png" height="40px" alt="logo">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a asp-controller="Home" asp-action="Articles" class="nav-link">Статьи</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Дискуссии</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Category" asp-action="List">Категории</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-controller="Author" asp-action="List">Авторы</a>
                </li>
                @if (User.IsInRole("Mod") || User.IsInRole("Admin"))
                {
                    <li class="nav-item">
                        <a asp-controller="Review" asp-action="All" class="nav-link">Ревью</a>
                    </li>
                }
                <li class="nav-item">
                    <a class="btn" style="background-color: #7B61FF; color: white; border-radius: 8px" asp-controller="Article" asp-action="Create">Написать статью</a>
                </li>
                <li class="nav-item ml-2">
                    <form method="post" asp-controller="Home" asp-action="Search">
                        <input class="form-control mr-sm-2" style="border-radius: 8px" type="search" name="search" placeholder="Найти статью" aria-label="Найти статью">
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                @if (_signInManager.IsSignedIn(User))
                {
                    var avatarPath = _userManager.GetUserAsync(User).Result.AvatarPath ?? "imgs/avatars/default.png";
                    <div class="dropdown">
                        <li class="nav-item row mr-auto" data-toggle="dropdown">
                            <a href="#" class="nav-link">@_userManager.GetUserAsync(User).Result.FirstName @_userManager.GetUserAsync(User).Result.LastName</a>
                            <img src="~/@avatarPath" alt="avatar" width="36" height="36" style="border-radius: 18px">
                        </li>
                        <div class="dropdown-menu" style="border-radius: 8px; right: 0; left: auto;" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-controller="Settings" asp-action="ChangePersonalData">Мой профиль</a>
                            <a class="dropdown-item" asp-controller="Review" asp-action="MyReviews">Мои ревью</a>
                            <a class="dropdown-item" asp-controller="Article" asp-action="MyDrafts">Мои черновики</a>
                            <a class="dropdown-item" href="#">Диалоги</a>
                            <form method="post" asp-controller="Account" asp-action="Logout">
                                <button class="dropdown-item" type="submit">Выйти</button>
                            </form>
                        </div>
                    </div>
                }
                else
                {
                    <li>
                        <a asp-controller="Account" asp-action="Login" class="btn btn-light" style="border: 1px solid lightgray; border-radius: 8px">Войти</a>
                    </li>
                    <li>
                        <a asp-controller="Account" asp-action="Register" class="btn btn-light ml-2" style="border: 1px solid lightgray; border-radius: 8px">Регистрация</a>
                    </li>
                }
            </ul>
        </div>
    </nav>
</header>
@RenderBody()

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

src/GeekStream.Web/Views/Shared/_sendCommentPartial.cshtml
@model GeekStream.Core.ViewModels.SendCommentViewModel

<form method="post" asp-controller="Comment" asp-action="SendComment" class="d-flex align-items-center py-2">
    <input hidden asp-for="ArticleId">
    <input class="py-1 mr-2" asp-for="Text" placeholder="Ваш комментарий" style="outline: none">
    <input type="submit" class="btn btn-light" style="border: 1px solid lightgray; border-radius: 8px">
</form>

src/GeekStream.Web/Views/Shared/_sendReviewCommentPartial.cshtml
@model GeekStream.Core.ViewModels.SendReviewCommentViewModel

<form method="post" asp-controller="Comment" asp-action="SendReviewComment" class="d-flex align-items-center py-2">
    <input hidden asp-for="ReviewId">
    <input class="py-1 mr-2" asp-for="Text" placeholder="Ваше сообщение" style="outline: none">
    <input type="submit" class="btn btn-light" style="border: 1px solid lightgray; border-radius: 8px">
</form>

src/GeekStream.Web/Views/Shared/_settingsMenuPartial.cshtml
@model string

@{
  var style1 = Model == "data" ? "nav-link active" : "nav-link";
  var style2 = Model == "pass" ? "nav-link active" : "nav-link";
  var style3 = Model == "avatar" ? "nav-link active" : "nav-link";
}

<div class="bg-light" style="border-radius: 16px 0 0 16px;">
    <div class="nav flex-column nav-pills">
        <a class="@style1" asp-controller="Settings" asp-action="ChangePersonalData">
          Данные профиля
        </a>
        <a class="@style2" asp-controller="Settings" asp-action="ChangePassword">
          Смена пароля
        </a>
        <a class="@style3" asp-controller="Settings" asp-action="ChangeAvatar">
          Смена аватара
        </a>
    </div>        
</div>