src/GeekStream.Web/Controllers/SettingsController.cs
using System.Threading.Tasks;
using GeekStream.Core.Services;
using GeekStream.Core.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;

namespace GeekStream.Controllers
{
    [Authorize]
    public class SettingsController : Controller
    {
        private readonly SettingsService _settingsService;
        private readonly IWebHostEnvironment _environment;

        public SettingsController(SettingsService settingsService, IWebHostEnvironment environment)
        {
            _settingsService = settingsService;
            _environment = environment;
        }
        
        [HttpGet]
        public async Task<IActionResult> ChangePersonalData()
        {
            return View(await _settingsService.GetUserPersonalData(User));
        }
        
        [HttpPost]
        public async Task<IActionResult> ChangePersonalData(ChangePersonalDataViewModel model)
        {
            if (!ModelState.IsValid) return View(model);
            
            var result = await _settingsService.ChangeUserPersonalData(model, User);
            if (result.Succeeded)
            {
                return RedirectToAction("ChangePersonalData");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            
            return View();
        }

        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (!ModelState.IsValid) return View();

            var result = await _settingsService.ChangeUserPassword(model, User);
            if (result.Succeeded)
            {
                return RedirectToAction("ChangePassword");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            
            return View();
        }

        [HttpGet]
        public IActionResult ChangeAvatar()
        {
            return View();
        }
        
        [HttpPost]
        public async Task<IActionResult> ChangeAvatar(ChangeAvatarViewModel model)
        {
            if (!ModelState.IsValid) return View();

            var result = await _settingsService.ChangeUserAvatar(User, model, _environment.WebRootPath);
            if (result.Succeeded)
            {
                return RedirectToAction("ChangeAvatar");
            }

            foreach (var error in result.Errors)
            {
                ModelState.AddModelError("", error.Description);
            }
            
            return View();
        }
    }
}

src/GeekStream.Web/Views/Settings/ChangeAvatar.cshtml
@using GeekStream.Core.Shared.Entities
@model GeekStream.Core.ViewModels.ChangeAvatarViewModel
@inject UserManager<AppUser> _userManager

@{
    ViewData["Title"] = "Сменить аватар";
    var avatarPath = _userManager.GetUserAsync(User).Result.AvatarPath ?? "imgs/avatars/default.png";
}

<div class="container">
    <div class="row text-center">
        <div class="col-md-2 offset-1 p-0 mt-3">
            @{ await Html.RenderPartialAsync("_settingsMenuPartial", "avatar"); }
        </div>
        <div class="col-md-6 bg-light mt-3" style="border-radius: 0 16px 16px 16px">
            <div class="col-md-10 offset-1 my-auto">
                <div class="col-md-auto" style="margin-top: 35px">
                    <img src="~/imgs/brand.png" alt="logo" height="40px">
                </div>
                <div class="col-md-auto mb-3">
                    <h2>Сменить аватар</h2>
                </div>
                <div>
                    <h4>Ваш текущий аватар</h4>
                    <img src="~/@avatarPath" alt="avatar" class="col-md-8">
                </div>
                <form enctype="multipart/form-data" asp-controller="Settings" asp-action="ChangeAvatar" method="post" class="text-left">
                    <label asp-for="Avatar"></label>
                    <div class="custom-file">
                        <input asp-for="Avatar" class="form-control custom-file-input">
                        <label class="custom-file-label">Выберите файл</label>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group d-flex justify-content-end" style="margin-bottom: 32px">
                        <button type="submit" class="btn col-md-auto" style="background-color: #7B61FF; color: white; border-radius: 8px;">Загрузить</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

src/GeekStream.Web/Views/Settings/ChangePassword.cshtml
@model GeekStream.Core.ViewModels.ChangePasswordViewModel

@{
    ViewData["Title"] = "Изменить пароль";
}

<div class="container">
    <div class="row text-center">
        <div class="col-md-2 offset-1 p-0 mt-3">
            @{ await Html.RenderPartialAsync("_settingsMenuPartial", "pass"); }
        </div>
        <div class="col-md-6 bg-light mt-3" style="border-radius: 0 16px 16px 16px">
            <div class="col-md-10 offset-1 my-auto">
                <div class="col-md-auto" style="margin-top: 35px">
                    <img src="~/imgs/brand.png" alt="logo" height="40px">
                </div>
                <div class="col-md-auto mb-3">
                    <h2>Изменить пароль</h2>
                </div>
                <form method="post" class="text-left" asp-controller="Settings" asp-action="ChangePassword">
                    <div class="form-group">
                        <label asp-for="OldPassword"></label>
                        <input asp-for="OldPassword" class="form-control" style="border-radius: 8px" placeholder="Предыдущий пароль">
                        <span asp-validation-for="OldPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="NewPassword"></label>
                        <input asp-for="NewPassword" class="form-control" style="border-radius: 8px" placeholder="Новый пароль">
                        <span asp-validation-for="NewPassword" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="ConfirmPassword"></label>
                        <input asp-for="ConfirmPassword" class="form-control" style="border-radius: 8px" placeholder="Повторите пароль">
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group d-flex justify-content-end" style="margin-bottom: 32px">
                        <button type="submit" class="btn col-md-auto" style="background-color: #7B61FF; color: white; border-radius: 8px;">Сменить пароль</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

src/GeekStream.Web/Views/Settings/ChangePersonalData.cshtml
@model GeekStream.Core.ViewModels.ChangePersonalDataViewModel

@{
    ViewData["Title"] = "Изменить данные аккаунта";
}

<div class="container">
    <div class="row text-center">
        <div class="col-md-2 offset-1 p-0 mt-3">
            @{ await Html.RenderPartialAsync("_settingsMenuPartial", "data"); }
        </div>
        <div class="col-md-6 bg-light mt-3" style="border-radius: 0 16px 16px 16px">
            <div class="col-md-10 offset-1 my-auto">
                <div class="col-md-auto" style="margin-top: 35px">
                    <img src="~/imgs/brand.png" alt="logo" height="40px">
                </div>
                <div class="col-md-auto mb-3">
                    <h2>Изменить данные профиля</h2>
                </div>
                <form method="post" class="text-left" asp-controller="Settings" asp-action="ChangePersonalData">
                    <div class="form-group row">
                        <div class="col-md-6">
                            <label asp-for="FirstName" style="font-size: 16px"></label>
                            <input asp-for="FirstName" class="form-control" style="border-radius: 8px" placeholder="Имя">
                            <span asp-validation-for="FirstName" class="text-danger"></span>
                        </div>
                        <div class="col-md-6">
                            <label asp-for="LastName"></label>
                            <input asp-for="LastName" class="form-control" style="border-radius: 8px" placeholder="Фамилия">
                            <span asp-validation-for="LastName" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label asp-for="Email"></label>
                        <input asp-for="Email" class="form-control" style="border-radius: 8px" placeholder="Ваша почта. Останется в секрете ;)">
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-group" style="margin-bottom: 32px">
                        <button type="submit" class="btn col-md-6 offset-6" style="background-color: #7B61FF; color: white; border-radius: 8px;">Изменить данные</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>