src/GeekStream.Web/Controllers/ArticleController.cs
using System.Threading.Tasks;
using GeekStream.Core.Services;
using GeekStream.Core.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GeekStream.Controllers
{
    public class ArticleController : Controller
    {
        private readonly CategoryService _categoryService;
        private readonly ArticleService _articleService;
        private readonly ReviewService _reviewService;

        public ArticleController(
            CategoryService categoryService,
            ArticleService articleService,
            ReviewService reviewService)
        {
            _categoryService = categoryService;
            _articleService = articleService;
            _reviewService = reviewService;
        }
        
        [HttpGet]
        [Authorize]
        public IActionResult Create()
        {
            ViewBag.Categories = _categoryService.GetCategories();
            return View();
        }
        
        [HttpGet]
        public IActionResult Read(int id)
        {
            var article = _articleService.GetArticleById(id);
            return View(new ReadArticleViewModel
            {
                Article = article
            });
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateArticleViewModel model)
        {
            ViewBag.Categories = _categoryService.GetCategories();
            if (!ModelState.IsValid) return View();
            var articleId = await _articleService.CreateArticle(model, User, false);
            if (articleId < 0)
            {
                ModelState.AddModelError("", "Не удалось создать статью");
                return View();
            }

            var reviewId = _reviewService.CreateReview(articleId);
            return RedirectToAction("Review", "Review", new { id = reviewId});
        }

        [HttpGet]
        [Authorize]
        public async Task<IActionResult> Draft(int id)
        {
            ViewBag.Categories = _categoryService.GetCategories();
            var model = await _articleService.GetDraftViewModelById(id, User);
            if (model == null) return NotFound();
            return View(model);
        }
        
        [HttpGet]
        [Authorize]
        public async Task<IActionResult> MyDrafts()
        {
            var model = await _articleService.GetUserDrafts(User);
            if (model == null) return NotFound();
            return View(model);
        }
        
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SaveAsDraft(CreateArticleViewModel model)
        {
            ViewBag.Categories = _categoryService.GetCategories();
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var articleId = await _articleService.CreateArticle(model, User, true);
            return RedirectToAction("Draft", new {id = articleId});
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult SaveDraft(DraftViewModel model)
        {
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var articleId = model.Id;
            _articleService.UpdateDraft(model);
            return RedirectToAction("Draft", new {id = articleId});
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult Publish(int reviewId)
        {
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var articleId = _articleService.Publish(reviewId);
            return RedirectToAction("Read", new {id = articleId});
        }
        
        [HttpGet]
        [Authorize]
        public IActionResult Unpublish(int articleId)
        {
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var article = _articleService.GetArticleById(articleId);
            if (User.Identity.Name != article.Author.UserName && !User.IsInRole("Admin") && !User.IsInRole("Mod"))
                return RedirectToAction("Articles", "Home");
            _articleService.Unpublish(articleId);
            return RedirectToAction("Draft", new {id = articleId});
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult Remove(int id)
        {
            if (!ModelState.IsValid) return RedirectToAction("Articles", "Home");
            var article = _articleService.GetArticleById(id);
            if (article == null || !article.IsDraft && article.PublishedDate != null) return RedirectToAction("Articles", "Home");
            if (User.Identity.Name != article.Author.UserName && !User.IsInRole("Admin") && !User.IsInRole("Mod"))
                return RedirectToAction("Articles", "Home");
            _articleService.Remove(article);
            return RedirectToAction("Articles", "Home");
        }
    }
}

src/GeekStream.Web/Controllers/CategoryController.cs
using GeekStream.Core.Shared.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace GeekStream.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryRepository _categoryRepository;

        public CategoryController(
            ICategoryRepository categoryRepository)
        {
            _categoryRepository = categoryRepository;
        }
        
        [HttpGet]
        public IActionResult Show(int id)
        {
            var category = _categoryRepository.GetCategoryById(id);
            return View(category);
        }
        
        [HttpGet]
        public IActionResult List()
        {
            var categories = _categoryRepository.GetCategories();
            return View(categories);
        }
    }
}

src/GeekStream.Web/Controllers/SubscriptionController.cs
using System.Threading.Tasks;
using GeekStream.Core.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace GeekStream.Controllers
{
    public class SubscriptionController : Controller
    {
        private readonly SubscriptionService _subscriptionService;

        public SubscriptionController(
            SubscriptionService subscriptionService)
        {
            _subscriptionService = subscriptionService;
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult SubscribeCategory(int categoryId)
        {
            _subscriptionService.SubscribeCategory(User, categoryId);
            return RedirectToAction("Show", "Category", new { id = categoryId });
        }
        
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> SubscribeAuthor(string authorId)
        {
            await _subscriptionService.SubscribeAuthor(User, authorId);
            return RedirectToAction("Show", "Author", new { id = authorId });
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult UnsubscribeCategory(int categoryId)
        {
            _subscriptionService.UnsubscribeCategory(User, categoryId);
            return RedirectToAction("Show", "Category", new { id = categoryId });
        }
        
        [HttpPost]
        [Authorize]
        public IActionResult UnsubscribeAuthor(string authorId)
        {
            _subscriptionService.UnsubscribeAuthor(User, authorId);
            return RedirectToAction("Show", "Author", new { id = authorId});
        }
    }
}

src/GeekStream.Web/Views/Category/List.cshtml
@model IEnumerable<GeekStream.Core.Shared.Entities.Category>

@{
    ViewData["Title"] = "Список категорий";
}

<div class="container pt-3">
    @foreach (var category in Model)
    {
        <div class="container bg-white mb-3" style="border-radius: 8px; padding: 24px">
            <div class="row align-items-center">
                <div class="col-md-auto d-flex flex-row align-items-center">
                    <a asp-controller="Category" asp-action="Show" asp-route-id="@category.Id" class="nav-link pl-2">@category.Name</a>
                </div>
            </div>
        </div>
    }
</div>

src/GeekStream.Web/Views/Category/Show.cshtml
@inject RatingService _ratingService
@inject SubscriptionService _subscriptionService
@using GeekStream.Core.Services
@model GeekStream.Core.Shared.Entities.Category

@{
    ViewData["Title"] = Model.Name;
}

<div class="container">
    <div class="row">
        @if (Model.BackgroundPath == null)
            {
                <div class="col-md-12" style="height: 200px; background-color: #7B61FF;"></div>
            }
            else
            {
                <img src="~/@Model.BackgroundPath" alt="Category background" height="200" class="col-md-auto">
            }
    </div>
    <div class="row bg-white align-items-center p-3">
        <div class="col-md-auto" style="background-color: #7B61FF; width: 48px; height: 48px; border-radius: 4px"></div>
        <div class="col-md-auto">@Model.Name</div>
        <form class="col-md-auto ml-auto" method="post">
            <input hidden name="categoryId" id="categoryId" value="@Model.Id">
            @if (_subscriptionService.IsUserSubscribedToCategory(User, Model.Id))
            {
                <input asp-controller="Subscription" asp-action="UnsubscribeCategory" class="btn" style="background-color: #7B61FF; color: white; border-radius: 8px" type="submit" value="Отписаться">
            }
            else
            {
                <input asp-controller="Subscription" asp-action="SubscribeCategory" class="btn" style="background-color: #7B61FF; color: white; border-radius: 8px" type="submit" value="Подписаться">   
            }
        </form>
    </div>
    <div class="row py-3">
        Статьи в этой категории
    </div>
    @foreach (var article in Model.Articles.Where(x => !x.IsDraft && x.PublishedDate != null))
        {
            <div class="container bg-white mb-3" style="border-radius: 8px; padding: 24px">
                <div class="row align-items-center">
                    <div class="col-md-auto">
                        @if (article.Category.IconPath == null)
                        {
                            <div style="width: 24px; height: 24px; background-color: #7B61FF; border-radius: 4px"></div>
                        }
                        else
                        {
                            <img src="~/@article.Category.IconPath" width="24" height="24" alt="CategoryIcon">
                        }
                    </div>
                    <a class="col-md-auto pl-0" href="#">@article.Category.Name</a>
                    <div class="col-md-auto text-muted small">@DateTime.Parse(article.PublishedDate.ToString()).ToString("dd/MM/yyyy HH:mm")</div>
                    <div class="col-md-auto ml-auto d-flex flex-row align-items-center">
                        @{
                            var avatarPath = article.Author.AvatarPath ?? "imgs/avatars/default.png";
                        }
                        <img src="~/@avatarPath" alt="avatar" width="24" height="24" style="border-radius: 18px">
                        <a href="#" class="nav-link pl-2">@article.Author.FirstName @article.Author.LastName</a>
                    </div>
                </div>
                <div class="row align-items-center">
                    <a class="text-muted" asp-controller="Article" asp-action="Read" asp-route-id="@article.Id">
                        <h5 class="col-md-auto">@article.Title</h5>
                    </a>
                </div>
                <div class="small text-muted">
                    @article.Content
                </div>
                <div class="row align-items-center py-2">
                    <img class="col-md-auto pr-0" height="20" src="~/imgs/comments.png" alt="Comments">
                    <div class="text-muted col-md-auto pl-1">
                        @article.Comments.Count
                    </div>
                    <div id="@article.Id" class="col-md-auto ml-auto d-flex align-items-center">
                        <button name="up" class="btn btn-sm @(await _ratingService.GetUserVote(User, article.Id) == 1 ? "btn-success" : "btn-outline-success") border-0 col-md-4 rounded-circle" style="outline: none; box-shadow: none">
                            +
                        </button>
                        <div name="rating" class="@(article.Rating >= 0 ? "text-success" : "text-danger") px-3">
                            @article.Rating
                        </div>
                        <button name="down" class="btn btn-sm @(await _ratingService.GetUserVote(User, article.Id) == -1 ? "btn-danger" : "btn-outline-danger") border-0 col-md-4 rounded-circle" style="outline: none; box-shadow: none">
                            -
                        </button>
                    </div>
                </div>
            </div>
        }
</div>

@section Scripts
{
    <script src="~/js/signalr/dist/browser/signalr.js"></script>
    <script type="application/javascript">
        "use strict";
        
        var connection = new signalR.HubConnectionBuilder().withUrl("/rating").build();
        
        connection.on("UpdateRating", function (articleId, rating, userVote) {
            const articleRating = document.getElementById(articleId).getElementsByTagName("div")[0];
            const buttons = document.getElementById(articleId).getElementsByTagName("button");
            
            articleRating.innerText = rating;
            if (rating >= 0) {
                articleRating.classList.remove("text-danger");    
                articleRating.classList.add("text-success");
            } else {
                articleRating.classList.remove("text-success");
                articleRating.classList.add("text-danger");   
            }
            
            if (userVote === 0) {
                buttons[0].classList.remove("btn-success");
                buttons[0].classList.add("btn-outline-success");
                buttons[1].classList.remove("btn-danger");
                buttons[1].classList.add("btn-outline-danger");
            } else if (userVote === 1) {
                buttons[0].classList.remove("btn-outline-success");
                buttons[0].classList.add("btn-success");
                buttons[1].classList.remove("btn-danger");
                buttons[1].classList.add("btn-outline-danger");
            } else if (userVote === -1) {
                buttons[0].classList.remove("btn-success");
                buttons[0].classList.add("btn-outline-success");
                buttons[1].classList.remove("btn-outline-danger");
                buttons[1].classList.add("btn-danger");
            }
        });
        
        connection.start().catch(function (err) {
            return console.error(err.toString());
        });
        
        const ups = document.getElementsByName("up");
        for(let i = 0; i < ups.length; i++) {
            ups[i].addEventListener("click", function (e) {
                connection.invoke("Vote", parseInt(this.parentElement.id), 1).catch(function (err) {
                    return console.error(err.toString());
                });  
            });
        }
        
        const downs = document.getElementsByName("down");
        for(let i = 0; i < downs.length; i++) {
            downs[i].addEventListener("click", function (e) {
                connection.invoke("Vote", parseInt(this.parentElement.id), -1).catch(function (err) {
                    return console.error(err.toString());
                });    
            })
        }
    </script>
}